### ISSUE TITLE
Update peaceiris/actions-gh-pages

### ISSUE THREAD

**Issue by peaceiris** [elswork/TestActions#1]
https://github.com/elswork/TestActions/blob/6f252440e8df9d7a1f02831a6e04c1ccc8102dce/.github/workflows/main.yml#L17

Please use the latest version and check the latest [README](https://github.com/peaceiris/actions-gh-pages#readme).

- [Releases · peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages/releases)

And, please do not use `GITHUB_TOKEN`, use `ACTIONS_DEPLOY_KEY` or `PERSONAL_TOKEN` 
  - cf. https://github.com/peaceiris/actions-gh-pages/issues/9

**Comment by elswork** [comment]
Thanks you very much for the advice.
